### ISSUE TITLE
Add CDx platform field and additional info field in oncokb-curation

### ISSUE THREAD

**Issue by calvinlu3** [oncokb/oncokb-transcript#105]
- [x] Add extra field for CDx platform
 - The platform is in the Approval Order Statement and should be a text box
- [x] Also add an `additionalInfo` field that is JSON, so that we can include any additional information that we may add in the future

**Comment by zhx828** [comment]
On hold until Ritika provides the full list of CDx

**Comment by calvinlu3** [comment]
Fixed in https://github.com/oncokb/oncokb-transcript/pull/108
